apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tor-role
subjects:
- kind: ServiceAccount
  name: tor
roleRef:
  kind: Role
  name: tor-role
  apiGroup: rbac.authorization.k8s.io

