apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor
  annotations:
    pv.beta.kubernetes.io/gid: "65533"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
