apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      serviceAccountName: tor
      initContainers:
      - name: init-tor
        image: bitnami/kubectl:latest
        command: ['sh', '-c', 'until nslookup tor; do echo waiting for tor; sleep 2; done;']
        command: ['kubectl', 'get', 'service', 'tor', '-o', 'jsonpath=''{.status.loadBalancer.ingress[0].ip}''']
      containers:
      - name: nginx
        image: jess/tor-relay
        ports:
        - containerPort: 9001
        env:
        - name: RELAY_NICKNAME
          value: "kubernetor"
        volumeMounts:
        - name: tor
          mountPath: /var/lib/tor/
      volumes:
      - name: tor
        persistentVolumeClaim:
          claimName: tor
    
