apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      serviceAccountName: tor
      initContainers:
      - name: init-tor
        image: bitnami/kubectl:latest
        command: ['/bin/sh']
        args: ['-c', 'kubectl get service tor -o jsonpath=''{.status.loadBalancer.ingress[0].ip}'' > /config/ip']
        volumeMounts:
        - name: tor
          mountPath: /var/lib/tor/
        - name: config
          mountPath: /config
      containers:
      - name: tor
        image: jess/tor-relay
        command: ['/bin/sh']
        args: ['-c', 'echo Address $(cat /config/ip) >>  /etc/tor/torrc.middle && ./run.sh']
        ports:
        - containerPort: 9001
        env:
        - name: RELAY_NICKNAME
          value: "kubernetor"
        volumeMounts:
        - name: tor
          mountPath: /var/lib/tor/
        - name: config
          mountPath: /config
      volumes:
      - name: tor
        persistentVolumeClaim:
          claimName: tor
      - name: config
        emptyDir: {}

 
