apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: 2018-03-04T17:01:39Z
  generation: 8
  labels:
    app: honeytrap
  name: honeytrap
  namespace: default
  resourceVersion: "2594688"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/honeytrap
  uid: b4a2ccdb-1fcd-11e8-92a1-42010a80024f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honeytrap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: honeytrap
    spec:
      containers:
      - args:
        - --config
        - https://gist.githubusercontent.com/andrewmichaelsmith/df6fde1555776bd57374fe584a5572a6/raw/4fcc29b4092df244c5d405fc30949c394061554a/gistfile1.txt
        command:
        - /honeytrap/honeytrap
        image: honeytrap/honeytrap@sha256:f76935f7806a5d70feccb89b222464d4d9517e662d3de060bb865016b5f5c7cd
        imagePullPolicy: Always
        name: honeytrap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-04T17:02:53Z
    lastUpdateTime: 2018-03-04T17:02:53Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
