kind: ConfigMap 
apiVersion: v1 
metadata:
  name: honeytrap
data:
  config.toml: |
    [listener]
    type="socket"
    
    [service.ssh-simulator]
    type="ssh-simulator"
    credentials=["root:root", "root:password"]
    
    [[port]]
    ports=["tcp/8022", "tcp/8023"]
    services=["ssh-simulator"]
    
    [service.telnet]
    type="telnet"
    server-name="WS-3244"
    
    [[port]]
    port="tcp/5900"
    services=["telnet"]

    [service.http01]
    type="http"
    server="Nginx"
    
    [[port]]
    port="tcp/8080"
    services=["http01"]

    [service.vnc]
    type="vnc"
    image="/data/images/desktop.png"
    server-name="WS-3244"
    
    [[port]]
    port="tcp/5900"
    services=["vnc"]

    [service.redis]
    type="redis"
    version="4.0.2"
    os="Linux 2.6.32-431.el6.x86_64 x86_64"
    
    [[port]]
    port="tcp/6379"
    services=["redis"]

    [service.smtp]
    type="smtp"
    
    [[port]]
    port="tcp/8025"
    services=["smtp"]


    
    [channel.console]
    type="console"

    [channel.es]
    type="elasticsearch"
    url="https://elk-es-http:9200/honeytrap"
    insecure=true
    username="honeytrap"
    password="honeytrap"
    
    [[filter]]
    channel=["console"]

    [[filter]]
    channel=["es"]
 
    
    [[logging]]
    output = "stdout"
    level = "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: honeytrap
spec:
  type: LoadBalancer
  ports:
  - port: 22
    name: "ssh"
    protocol: TCP
    targetPort: 8022
  - port: 23
    name: "telnet"
    protocol: TCP
    targetPort: 8023
  - port: 25
    name: "smtp"
    protocol: TCP
    targetPort: 8025
  - port: 80
    name: "http"
    protocol: TCP
    targetPort: 8080
  - port: 5900
    name: "vnc"
    protocol: TCP
    targetPort: 5900
  - port: 6379
    name: "redis"
    protocol: TCP
    targetPort: 6379
  selector:
    app: honeytrap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeytrap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honeytrap
  template:
    metadata:
      labels:
        app: honeytrap
    spec:
      containers:
      - name: honeytrap
        image: honeytrap/honeytrap
        volumeMounts:
        - name: config-volume
          mountPath: /config/
      volumes:
        - name: config-volume
          configMap:
            name: honeytrap

